# https://taskfile.dev

version: "3"

includes:
  build:
    taskfile: ./docker
  tests:
    taskfile: ./tests

tasks:
  start:
    desc: start application
    cmds:
      - python3 src/sau/__main__.py -c configs/config.yaml
  pypi:
    desc: build & upload application
    cmds:
      - rm -rf dist/
      - rm -rf build/
      - python3 -m build
      - python3 -m twine upload --repository pypi dist/*
  compose-up:
    desc: "docker compose up"
    cmds:
      - task: compose-build
      - docker-compose up -d
  compose-down:
    desc: "docker compose down"
    cmds:
      - docker-compose down
  compose-build:
    desc: "build docker compose images"
    cmds:
      - docker-compose build
