# https://taskfile.dev

version: "3"

vars:
  DOCKER_REGISTRY: ugwuanyi
  IMAGE_NAME: "sau"
  IMAGE_VERSION: 0.0.5

tasks:
  build_template:
    desc: build docker image
    preconditions:
      - test ! -z "{{.IMAGE_NAME}}"
    cmds:
      - echo "image={{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.IMAGE_VERSION}}"
      - docker buildx ls | grep "temp_builder" || docker buildx create --name=temp_builder
      - docker buildx use temp_builder
      - docker buildx build -f docker/Dockerfile --build-arg="VERSION={{.IMAGE_VERSION}}" --push --platform linux/amd64,linux/arm64 --no-cache --tag {{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.IMAGE_VERSION}} .
      - docker buildx rm temp_builder
    internal: true
    silent: false
  all:
    desc: build awshealth image
    cmds:
      - task: build_template
      - task: build_template
        vars:
          IMAGE_VERSION: latest
  local:
    desc: "build docker image"
    cmds:
      - |
        docker build --build-arg="VERSION=dev" -t sau:dev -f docker/Dockerfile .
  update:
    desc: update build details
    cmds:
      - sed -i '' -E "s/BUILD_DATE = .*/BUILD_DATE = \"$(date '+%Y-%m-%d %H:%M')\"/" {{.FILE}}
      - sed -i '' -E "s/VERSION = .*/VERSION = \"{{.IMAGE_VERSION}}\"/" {{.FILE}}
      - sed -i '' -E "s/version = .*/version = \"{{.IMAGE_VERSION}}\"/" pyproject.toml
    vars:
      FILE: src/sau/__main__.py
