{
 "title": "Stopped and Unattached (SaU) Graph",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Stopped EC2 Instance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EC2 Stopped Instances Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (sau_ec2_stopped_instances_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EC2 Stopped Instances Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "targets": [
    { "expr": "sau_ec2_stopped_instances" }
   ]
  },
  { "title": "EBS Volumes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "EBS Volumes States Total",
   "type": "stat",
   "description": "Sum total for EBS volume states error or unattached.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, status) (sau_ebs_volumes_total)",
     "legendFormat": "{{region}} {{status}}"
    }
   ]
  },
  {
   "title": "EBS Volumes States",
   "type": "table",
   "description": "Tabular display for all volumes state (error or unattached)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "sau_ebs_volumes" }
   ]
  }
 ]
}