# list of regions to scrape: REQUIRED
regions:
  - eu-central-1
  - eu-west-1

# exporter port. Defaults to 9191
exporter_port: 9191

# Logging configuration
logging:
  # Number of log files to retain after log rotation
  retention: 7
  # log directory. defaults to current working directory
  directory: "."
  # log level (debug, info, warn, error). Defaults to info
  level: info
  # which log handler to use (stdout, file, both). Defaults to both.
  # stdout will only log to stdout
  # file will only log to the specified file
  # both will log to both stdout and file
  handler: both

# Optional: Tags to exclude from monitoring
#           The tag values are case insensitive
exclude_tags:
  inv_environment_id:
    - development
  inv_cluster_type:
    - hansen
