name: docker

on:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  docker_matrix:
    strategy:
      matrix:
        image_tag: ["${{ github.ref_name }}", "latest"]
        registry: ["docker.io", "ghcr.io"]
        include:
          - registry: docker.io
            username: ugwuanyi
            image: ugwuanyi/sau
          - registry: ghcr.io
            username: emylincon
            image: ghcr.io/emylincon/sau
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: matrix.registry == 'ghcr.io'
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: emylincon
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        if: matrix.registry == 'docker.io'
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: ugwuanyi
          password: ${{  secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ ! (github.ref_type == 'branch' && matrix.image_tag == 'latest') }}
        with:
          push: true
          tags: "${{ matrix.image }}:${{ matrix.image_tag }}"
          context: .
          file: docker/Dockerfile
          labels: "org.opencontainers.image.source=https://github.com/emylincon/sau"
          platforms: linux/amd64,linux/arm64
          build-args: APP_VERSION=${{ github.ref_name }}
          no-cache: true
