name: docker

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:

jobs:
  docker_matrix:
    strategy:
      matrix:
        image_tag: ["latest"]
        registry: ["docker.io"]
        include:
          - registry: docker.io
            username: ugwuanyi
            image: ugwuanyi/apps-greet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: matrix.registry == 'ghcr.io'
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: emylincon
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        if: matrix.registry == 'docker.io'
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: ugwuanyi
          password: ${{  secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "${{ matrix.image }}:${{ matrix.image_tag }}"
          context: .
          file: docker/Dockerfile
          labels: "org.opencontainers.image.source=https://github.com/emylincon/sau"
          platforms: linux/amd64,linux/arm64
          build-args: ["name=james", "age=11"]
          no-cache: true
